<a href="https://colab.research.google.com/github/AkshayK25/SARS-COV-2-Infection-Probability-Detector/blob/master/Main_File.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

#**Reading Data**


In [0]:
df = pd.read_csv("https://raw.githubusercontent.com/AkshayK25/SARS-COV-2-Infection-Probability-Detector/master/Covid_assum.csv")

In [34]:
df.head()

Age       Fever  Body_Pain  Runny_Nose  Diff_Breath  Infection_Probability
0   45   99.822559          0           0           -1                      0
1   87  107.049867          1           0            0                      1
2   35  104.454592          1           1           -1                      1
3   15  102.590211          1           0           -1                      1
4   45  101.023338          1           1            1                      1

In [35]:
df.tail()

Age       Fever  ...  Diff_Breath  Infection_Probability
3290   89  106.382599  ...            0                      1
3291   22  103.710368  ...            0                      1
3292   75  101.067890  ...           -1                      1
3293   62  106.606564  ...            0                      1
3294   63  103.780892  ...            0                      1

[5 rows x 6 columns]

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3295 entries, 0 to 3294
Data columns (total 6 columns):
Age                      3295 non-null int64
Fever                    3295 non-null float64
Body_Pain                3295 non-null int64
Runny_Nose               3295 non-null int64
Diff_Breath              3295 non-null int64
Infection_Probability    3295 non-null int64
dtypes: float64(1), int64(5)
memory usage: 154.6 KB


In [37]:
df['Diff_Breath'].value_counts()

-1    1163
 0    1104
 1    1028
Name: Diff_Breath, dtype: int64

In [38]:
df.describe()

Age        Fever  ...  Diff_Breath  Infection_Probability
count  3295.000000  3295.000000  ...  3295.000000            3295.000000
mean     52.643399   102.987670  ...    -0.040971               0.787253
std      21.979457     2.302143  ...     0.814536               0.409312
min      15.000000    98.000949  ...    -1.000000               0.000000
25%      34.000000   101.267198  ...    -1.000000               1.000000
50%      53.000000   103.012075  ...     0.000000               1.000000
75%      71.000000   104.732559  ...     1.000000               1.000000
max      90.000000   107.984098  ...     1.000000               1.000000

[8 rows x 6 columns]

**Train Test Splitting**

In [0]:
import numpy as np


In [0]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [0]:
train_data , test_data = data_split(df,0.2)

In [42]:
train_data

Age       Fever  ...  Diff_Breath  Infection_Probability
2989   27  105.658328  ...           -1                      1
2882   31   99.776036  ...            0                      0
2643   52  100.161226  ...           -1                      0
436    70  101.033328  ...            0                      1
2215   71  103.189548  ...            0                      1
...   ...         ...  ...          ...                    ...
1095   51   98.257737  ...           -1                      0
1130   27  102.953270  ...            0                      1
1294   90  101.336534  ...            0                      1
860    39  105.205243  ...           -1                      1
3174   56  103.441167  ...           -1                      1

[2636 rows x 6 columns]

In [43]:
test_data

Age       Fever  ...  Diff_Breath  Infection_Probability
3101   15  104.362893  ...            0                      1
3164   35  102.446971  ...            0                      1
3102   44  103.085471  ...            1                      1
1947   38   99.543029  ...           -1                      0
2400   74  101.758019  ...           -1                      1
...   ...         ...  ...          ...                    ...
802    26  103.114566  ...            1                      1
2308   42  102.031836  ...            1                      1
839    44  101.370864  ...           -1                      1
817    53  104.982842  ...            0                      1
69     28  102.468727  ...            1                      1

[659 rows x 6 columns]

In [0]:
X_train = train_data[['Age','Fever','Body_Pain','Runny_Nose','Diff_Breath']]
X_test = test_data[['Age','Fever','Body_Pain','Runny_Nose','Diff_Breath']]

In [45]:
X_train

Age       Fever  Body_Pain  Runny_Nose  Diff_Breath
2989   27  105.658328          1           0           -1
2882   31   99.776036          0           0            0
2643   52  100.161226          1           0           -1
436    70  101.033328          1           1            0
2215   71  103.189548          1           0            0
...   ...         ...        ...         ...          ...
1095   51   98.257737          0           0           -1
1130   27  102.953270          1           0            0
1294   90  101.336534          1           0            0
860    39  105.205243          1           1           -1
3174   56  103.441167          1           0           -1

[2636 rows x 5 columns]

In [46]:
X_test

Age       Fever  Body_Pain  Runny_Nose  Diff_Breath
3101   15  104.362893          1           0            0
3164   35  102.446971          1           0            0
3102   44  103.085471          1           0            1
1947   38   99.543029          0           1           -1
2400   74  101.758019          1           1           -1
...   ...         ...        ...         ...          ...
802    26  103.114566          1           0            1
2308   42  102.031836          1           0            1
839    44  101.370864          1           0           -1
817    53  104.982842          1           0            0
69     28  102.468727          1           1            1

[659 rows x 5 columns]

In [47]:
X_train.to_numpy()

array([[ 27.        , 105.6583285 ,   1.        ,   0.        ,
         -1.        ],
       [ 31.        ,  99.77603634,   0.        ,   0.        ,
          0.        ],
       [ 52.        , 100.1612259 ,   1.        ,   0.        ,
         -1.        ],
       ...,
       [ 90.        , 101.3365344 ,   1.        ,   0.        ,
          0.        ],
       [ 39.        , 105.2052432 ,   1.        ,   1.        ,
         -1.        ],
       [ 56.        , 103.441167  ,   1.        ,   0.        ,
         -1.        ]])

In [48]:
X_test.to_numpy()

array([[ 15.       , 104.3628933,   1.       ,   0.       ,   0.       ],
       [ 35.       , 102.446971 ,   1.       ,   0.       ,   0.       ],
       [ 44.       , 103.0854713,   1.       ,   0.       ,   1.       ],
       ...,
       [ 44.       , 101.3708639,   1.       ,   0.       ,  -1.       ],
       [ 53.       , 104.9828418,   1.       ,   0.       ,   0.       ],
       [ 28.       , 102.4687269,   1.       ,   1.       ,   1.       ]])

In [0]:
Y_train = train_data[['Infection_Probability']].to_numpy().reshape(2636,)
Y_test = test_data[['Infection_Probability']].to_numpy().reshape(659,)

In [50]:
Y_train

array([1, 0, 0, ..., 1, 1, 1])

In [51]:
Y_test

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,

In [0]:
from sklearn.linear_model import LogisticRegression

In [53]:
clf = LogisticRegression()
clf.fit(X_train,Y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
input_features = [35,103,1,1,-1]
infprob = clf.predict_proba([input_features])[0][1]

In [58]:
infprob*100

99.99998975254375